SystemOrganization addCategory: #'J2Inferer-Tests-TestCode'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Collections'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Contexts'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Escalonated'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Inheritance'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Messages'!
SystemOrganization addCategory: 'J2Inferer-Tests-TestCode-Simple'!
