SystemOrganization addCategory: #J2Inferer!
SystemOrganization addCategory: 'J2Inferer-AST'!
SystemOrganization addCategory: 'J2Inferer-NewVariables'!
SystemOrganization addCategory: 'J2Inferer-PredefinedMethods'!
SystemOrganization addCategory: 'J2Inferer-Tasks'!
SystemOrganization addCategory: 'J2Inferer-Tasks-Queue'!
SystemOrganization addCategory: 'J2Inferer-Utils'!
SystemOrganization addCategory: 'J2Inferer-Variables'!
